### ISSUE TITLE
Question : does it work with Apple mps ?

### ISSUE THREAD

**Issue by edmondja** [Azure/MS-AMP#110]
Question : does it work with Apple mps ?

**Comment by wkcn** [comment]
Hi @edmondja , thanks for your attention to our work!

MS-AMP does not support Apple MPS yet. The reason is that the [FP8 data type](https://github.com/Azure/MS-AMP/blob/main/msamp/optim/common.h#L26) (native or simulation), [the type conversion](https://github.com/Azure/MS-AMP/blob/main/msamp/te/extension.py#L14) between FP8 and high-precision data types such as FP16/BF16/FP32, as well as [the FP8 optimizer](https://github.com/Azure/MS-AMP/blob/main/msamp/optim/adamw.cu) are implemented using CUDA.

**Comment by edmondja** [comment]
🥲thanks
